org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21
minecraft_version_range=[1.21,1.22)
forge_version=51.0.33
forge_version_range=[51,)
loader_version_range=[51,)

mapping_channel=official

mapping_version=1.21

mod_id=galosphere
mod_name=Galosphere
mod_license=All-Rights-Reserved
mod_version=1.4.2
mod_group_id=net.orcinus.galosphere
mod_authors=Orcinus
mod_description=Galosphere aims to improve the underground by adding new biomes and feature
