modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    logoFile= "galosphere.png"
    authors="${mod_authors}"
    description='''
    Galosphere is a mod that aims to overhaul the underground

    Author:
    - Orcinus

    Contributors:
    - Ninni
    - bunten

    '''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"

[[mixins]]
    config="galosphere.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
